disabled_rules:
- line_length
- trailing_whitespace
- function_parameter_count
- identifier_name
- force_cast
- function_body_length
- nesting
- orphaned_doc_comment
- shorthand_operator
- legacy_constructor

excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Pods
  - HealthFoodMe/Application/AppDelegate.swift
  - HealthFoodMe/Application/SceneDelegate.swift
